/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

//SUMA
float *
suma_1_svc(inputs arg1,  struct svc_req *rqstp)
{
	static float  result;

	result = arg1.num1+arg1.num2;

	printf("Se obtuvo la solicitud, y se ha enviado la respuesta: %.2f\n", result);

	return &result;
}
//RESTA
float *
resta_1_svc(inputs arg1,  struct svc_req *rqstp)
{
	static float  result;

	result = arg1.num1-arg1.num2;

	printf("Se obtuvo la solicitud, y se ha enviado la respuesta: %.2f\n", result);

	return &result;
}
//MULTIPLICACION
float *
mul_1_svc(inputs arg1,  struct svc_req *rqstp)
{
	static float  result;

	result = arg1.num1*arg1.num2;

	printf("Se obtuvo la solicitud, y se ha enviado la respuesta: %.2f\n", result);

	return &result;
}
//DIVISION
float *
div_1_svc(inputs arg1,  struct svc_req *rqstp)
{
	static float  result;

	result = arg1.num1/arg1.num2;

	printf("Se obtuvo la solicitud, y se ha enviado la respuesta: %.2f\n", result);

	return &result;
}
